name: "StackSpot Workflow Execution Bind"
description: "StackSpot Workflow"
author: "StackSpot"
branding:
  icon: "truck"
  color: "purple"
inputs:
  client-id:
    description: "Client ID StackSpot"
    required: true
  client-secret:
    description: "Client Secret StackSpot"
    required: true
  realm:
    description: "Realm StackSpot"
    required: true
  execution-id:
    description: "Workflow dispatched execution id"
    required: true
  stackspot-workflow-job:
      description: "Name of StackSpot Workflow Job"
      required: true
  idm-base-url:
    description: "StackSpot IDM base url"
    required: false
    default: "https://idm.stackspot.com"
  workflow-api-base-url:
    description: "Workflow API base url"
    required: false
    default: "https://workflow-api.v1.stackspot.com"
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh ${{ inputs.client-id }} ${{ inputs.client-secret }} ${{ inputs.realm }} ${{ inputs.idm-base-url }} ${{ inputs.workflow-api-base-url }} ${{ inputs.execution-id }} ${{ inputs.stackspot-workflow-job}}
      shell: bash
