name: Test StackSpot Workflow action

on:
  workflow_dispatch:
    inputs:
      execution-id:
        description: "Workflow dispatched execution id"
        required: true
      stackspot-workflow-job:
          description: "Name of StackSpot Workflow Job"
          required: true
      realm:
        description: "Realm StackSpot"
        required: true

jobs:
  stackspot-workflow-bind-scm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Action of Bind
        uses: ./
        with:
          execution-id: "${{ github.event.inputs.execution-id }}"
          stackspot-workflow-job: "${{ github.event.inputs.stackspot-workflow-job }}"
          realm: "${{ github.event.inputs.realm }}"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"

